import Header from "@/components/Header";
import ServicesContents from "@/components/ServicesContents";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Grant Imbo - Services",
  description: "Generated by create next app",
};

export default function Services() {
  return (
    <>
      <Header hidemenu={true} />
      <ServicesContents />
    </>
  );
}
