import AboutContents from "@/components/AboutContents";
import Header from "@/components/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <>
      <Header hidemenu={true} />
      <AboutContents />
    </>
  );
}
