export const featured_projects = [
  {
    title: "Simple Money Tracker",
    link: "/projects/simple-money-tracker",
    target: "_self",
    thumbnail: "/imgs/featured_projects/expense-tracker.jpg",
    tags: ["Next.js", "Firebase"],
    description: `Sleek and minimal expense tracker tool that enables users to have better control over their finances.`,
  },
  {
    title: "2014 Personal Website",
    link: "/projects/slanttex/",
    target: "_self",
    thumbnail: "/imgs/featured_projects/slanttex.jpg",
    tags: ["WordPress", "Photoshop"],
    description: `Personally, one of my favorite rebuilds on my site. It incorporates minimal JS and laverages CSS3 transitions.`,
  },
  {
    title: "Stitch",
    link: "/projects/stitch",
    target: "_self",
    thumbnail: "/imgs/featured_projects/stitch.jpg",
    tags: ["Figma", "Photoshop", "Next.js"],
    description: `NFT marketplace allowing healthcare professionals to tokenize and trade high-quality medical images.`,
  },
  // {
  //   title: "Product Visualizations",
  //   link: "https://simple-money-tracker.vercel.app/",
  //   thumbnail: "/imgs/featured_projects/visualizations.jpg",
  //   tags: ["Cinema 4D", "Photoshop"],
  //   description: `Creating multimedia assets for web and print, and crafting WordPress plugins and themes.`,
  // },
  {
    title: "Motion Designs",
    link: "/projects?tag=motion",
    target: "_self",
    thumbnail: "/imgs/featured_projects/motion.jpg",
    tags: ["Cinema 4D", "Photoshop"],
    description: `Dive into a curated archive showcasing my personal portfolio of dynamic motion designs.`,
  },
  {
    title: "Car Renders",
    link: "/projects?tag=cars",
    target: "_self",
    thumbnail: "/imgs/featured_projects/car-renders.jpg",
    tags: ["WordPress", "After Effects", "Photoshop", "Vegas"],
    description: `A collection of 3D car artworks where each detail is personally handcrafted and modeled from scratch.`,
  },
  {
    title: "Typography",
    link: "/projects?tag=typography",
    target: "_self",
    thumbnail: "/imgs/featured_projects/type.jpg",
    tags: ["Cinema 4D", "Photoshop"],
    description: `Explore my collection of typography artworks, where each detail has been personally crafted with attention.`,
  },
];
