import Header from "@/components/Header";
import ProjectWrap from "@/components/ProjectWrap";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Grant Imbo - Home",
  description: "Generated by create next app",
};

export default function Projects() {
  return (
    <>
      <Header fixed={true} />
      <ProjectWrap />
    </>
  );
}
