import type { Metadata } from "next";
import "../styles/global.scss";

export const metadata: Metadata = {
  title: "Grant Imbo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=block"
      />
      <link rel="icon" href="/imgs/favicon.png" />
      <body>{children}</body>
    </html>
  );
}
