import Experience from "@/components/Experience";
import FeaturedProjects from "@/components/FeaturedProjects";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import HomeIntro from "@/components/HomeIntro";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Grant Imbo - Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <Header hidemenu={true} />

      <HomeIntro />
      <Experience />
      <FeaturedProjects />
      <Footer />
    </>
  );
}
