"use client";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Projects",
  description: "Generated by create next app",
};

export default function NotFound() {
  return (
    <>
      <section className="flex h-[90vh] items-center justify-center text-center">
        <div>
          <h1 className="text-5xl font-bold">404 - Error</h1>
          <h3 className="mb-0 text-2xl font-medium text-eggblue">
            Page Not Found
          </h3>
          <p className="leading-snug text-softgray">
            The page you are looking for might have been moved or no longer
            exists.
          </p>
        </div>
      </section>
    </>
  );
}
